### ISSUE TITLE
SBOM db image requires authentication for pulling

### ISSUE THREAD

**Issue by phantasia15** [cisco-open/kubei#114]
#### What happened:

The SBOM db image seems to require authentication to pull.

```
$ docker pull ghcr.io/cisco-open/kubeclarity-sbom-db:v2.0.0
Error response from daemon: Head https://ghcr.io/v2/cisco-open/kubeclarity-sbom-db/manifests/v2.0.0: unauthorized
```

#### What you expected to happen:

It should not require authentication.

#### How to reproduce it (as minimally and precisely as possible):

`$ docker pull ghcr.io/cisco-open/kubeclarity-sbom-db:v2.0.0`

**Comment by FrimIdan** [comment]
Hi @phantasia15, thanks for reaching out, the images are now public. You are welcome to continue testing and feedback on the new release.
