### ISSUE TITLE
k8s.io/kubernetes imports are not recommended

### ISSUE THREAD

**Issue by justaugustus** [cisco-open/kubei#79]
@cisco-open/kubei-maintainers -- From @liggitt in https://github.com/kubernetes/kubernetes/issues/90358#issuecomment-617859364:

> > go: k8s.io/kubernetes@v1.18.2 requires ...
> 
> This is caused by depending on k8s.io/kubernetes directly as a library, which is not supported. The components intended to be used as libraries are published as standalone modules like k8s.io/api, k8s.io/apimachinery, k8s.io/client-go, etc, and can be referenced directly.
> 
> If you want to do this anyway, see discussion in https://github.com/kubernetes/kubernetes/issues/79384 about how you can workaround the v0.0.0 requirements.

Let's please remove the dep from https://github.com/cisco-open/kubei/blob/651fb9a41e88e3c62b2f0ea002a926fea07645f2/go.mod#L18.

Consider the suggestions in https://pkg.go.dev/github.com/google/go-containerregistry/pkg/authn as alternatives.

**Comment by justaugustus** [comment]
@cisco-open/kubei-maintainers -- Updates on this?

**Comment by FrimIdan** [comment]
@justaugustus it will be resolved once kubei v2 will be released
