### ISSUE TITLE
OOM Killed Scanned pod job

### ISSUE THREAD

**Issue by hackerup** [cisco-open/kubei#89]
Target namespace one of deployment scanned image pod job getting killed due to OOM resulting scan failure (succeeded state as false)

Please help how to increase the memory resources on scanned pod before the scan

**Comment by FrimIdan** [comment]
Hi @hackerup, currently the only option you have to increase scanners resources will be to build your own kubei deployment.

The resource values are hard coded [here for the vulnerability scanner](https://github.com/cisco-open/kubei/blob/main/pkg/scanner/job-manager.go#L284-L292) and [here for the CIS docker benchmark scanner](https://github.com/cisco-open/kubei/blob/main/pkg/scanner/job-manager.go#L330-L338).

We are working on a big refactoring for kubei and in that release we will make the resources configurable

**Comment by hackerup** [comment]
@fri

> Hi @hackerup, currently the only option you have to increase scanners resources will be to build your own kubei deployment.
> 
> The resource values are hard coded [here for the vulnerability scanner](https://github.com/cisco-open/kubei/blob/main/pkg/scanner/job-manager.go#L284-L292) and [here for the CIS docker benchmark scanner](https://github.com/cisco-open/kubei/blob/main/pkg/scanner/job-manager.go#L330-L338).
> 
> We are working on a big refactoring for kubei and in that release we will make the resources configurable

Thanks for the rapid response I will try the above workaround

**Comment by hackerup** [comment]
Worked Thankyou
